title: AnneGentle.GitHub.io
description: Anne Gentle works as a developer experience manager at Cisco DevNet, supporting developers who automate workflows for consistent, repeatable uses of infrastructure. She uses open-source techniques for API design, documentation, dev ops, and developer support.  
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
