title: AnneGentle.GitHub.io
description: Anne Gentle works as a Director of the developer experience at Cisco DevNet in the developer relations program, supporting developers who automate workflows for consistent, repeatable infrastructure uses. She uses open-source techniques for API design, documentation, dev ops, and developer support.  
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
